kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: "pvc-7c184bca-3477-4fef-b8b7-41acb54ebc8c"
  storageClassName: standard-rwo